# Generated by Django 4.2.3 on 2023-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class1Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
    ]
