# Generated by Django 4.2.3 on 2023-09-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_class1result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class1Result',
        ),
    ]
