# Generated by Django 4.2.3 on 2023-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_class1result'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D', 'D'), ('E1', 'E1'), ('E2', 'E2')], max_length=50, null=True),
        ),
    ]
