# Generated by Django 4.2.3 on 2023-09-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subject_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class1Result',
        ),
    ]
