# Generated by Django 4.2.3 on 2023-09-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_result_mark_class_subject_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_subject',
            name='std',
        ),
        migrations.AddField(
            model_name='subject',
            name='std',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.result'),
        ),
    ]
