# Generated by Django 4.2.3 on 2023-09-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_class_subject_std_subject_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='std',
        ),
    ]
