# Generated by Django 4.2.3 on 2023-09-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subject_grade_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
