# Generated by Django 4.2.3 on 2023-09-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_subject_grade_remove_subject_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D', 'D'), ('E1', 'E1'), ('E2', 'E2')], max_length=50, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.result')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subject')),
            ],
        ),
    ]
