# Generated by Django 4.2.5 on 2023-09-14 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_user_division_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_coordinator',
        ),
        migrations.AddField(
            model_name='event',
            name='co_coordinator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
