# Generated by Django 4.2.5 on 2023-09-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_event_co_coordinator_event_co_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='oordinator',
            new_name='coordinator',
        ),
    ]
