# Generated by Django 4.2.5 on 2023-09-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_fees_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_open_date', models.DateField()),
                ('admission_close_date', models.DateField()),
                ('admission', models.BooleanField(default=True)),
            ],
        ),
    ]
