# Generated by Django 4.2.5 on 2023-09-19 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField()),
                ('lastName', models.CharField()),
                ('father_name', models.CharField()),
                ('mother_name', models.CharField()),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('country', models.CharField()),
                ('zipcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('phonenumber', models.ImageField(upload_to='', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('emailaddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('bloodgroup', models.CharField(blank=True, null=True)),
                ('studentphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('admission_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.admission')),
            ],
        ),
    ]
