# Generated by Django 4.2.5 on 2023-09-19 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_admissionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='phonenumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
