# Generated by Django 4.2.5 on 2023-09-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_admissionform_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='admission_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.admission'),
        ),
    ]
