# Generated by Django 4.2.5 on 2023-10-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
